[package]
name = "mpc-frost-dalek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
frost-dalek = "0.2.3"
rand = "0.7"
chrono = "0.4.19"
sha2 = "0.10"
hex = "0.4"