version: "3"

services:
  server1:
    image: diks-tits:latest
    environment:
      SERVER_INDEX: 1
    volumes:
      - ./config/:/config/
    ports:
      - 8081:8080
  server2:
    image: diks-tits:latest
    environment:
      SERVER_INDEX: 2
    volumes:
      - ./config/:/config/
    ports:
      - 8082:8080
  server3:
    image: diks-tits:latest
    environment:
      SERVER_INDEX: 3
    volumes:
      - ./config/:/config/
    ports:
      - 8083:8080