[package]
name = "demo_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version="0.11", features=["json"]}
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
frost-dalek = { path = "../frost-dalek"}
sha2 = "0.10"
serde_json = "1"
hex = "0.4"